services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=loj'
      - 'POSTGRES_PASSWORD=loj'
      - 'POSTGRES_USER=loj'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
